[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@sparticuz/chromium-min/**",
    "node_modules/puppeteer-core/**"
  ]


